# Generated by Django 4.2.4 on 2023-08-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_rename_image_skill_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='picture',
            new_name='image',
        ),
    ]
